<?php echo $this->getChildHtml('sticky.nav') ?>
<?php
$store = Mage::app()->getStore();
$code = $store->getCode();
$custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
    <style>

    </style>
<div class="header-container type8">
    <div class="">
        <div class="header container">
            <div class="">
                <div class="col-12 col-sm-4 col-md-4 banner-top">
                    <?php if ($this->getIsHomePage()): ?>
                        <h1 class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><a
                                href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>"
                                class="logo"><img src="<?php echo $this->getLogoSrc(); ?>"
                                                  alt="<?php echo $this->getLogoAlt(); ?>"/></a></h1>
                    <?php else: ?>
                        <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>"
                           class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><img
                                src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>"/></a>
                    <?php endif; ?>
                </div>

                <div class="col-12 col-sm-8 col-md-8">
                    <div class="row">
                        <div class="cart-area">
                            <div class="top-links-area">
                                <div class="top-links-icon"><a
                                        href="javascript:void(0)"><?php echo $this->__("links"); ?></a>
                                </div>
                                <?php echo $this->getChildHtml('topLinks'); ?>
                            </div>
                            <div class="menu-icon">
                                <a href="javascript:void(0)" title="<?php echo $this->__('Menu'); ?>">
                                    <i class="fa fa-bars"></i>
                                </a>
                            </div>
                            <div class="switcher-area">
                                <?php
                                $store_currency = $this->getChildHtml('store_currency');
                                //                        $store_language = $this->getChildHtml('store_language');
                                ?>
                                <?php echo $store_currency; ?>
                                <!--                        --><?php //echo $store_language; ?>
                                <!--                        --><?php //echo $this->getChildHtml('compare_link'); ?>
                                <?php echo $this->getChildHtml('minicart'); ?>
                            </div>
                        </div>
                        <?php echo $this->getChildHtml("demo_header_tooltip"); ?>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-md-7">
                            <p class="text-header">Local, sustainable and organic meat</p>
                        </div>
                        <div class="col-sm-6 col-md-5">
                            <?php echo $this->getChildHtml('topSearch'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <div class="bot-menu row">
        <div class="container">
            <div class="col-md-12">
                <p style="margin: inherit">We deliver to metro areas in Sydney, Melbourner and Canberra for a flat  $10 • See if we deliver  to your  area <span class="glyphicon glyphicon-chevron-right"></span></p>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="top-banner">
            <span class="beef">BEEF</span>
        </div>
    </div>
    <div class="container shop-content">
        <div class="shop-our">
            <span class="shop">Shop Our Entire Beef Range</span><br/>
            <input type="button" name="shop-all" class="shop-all" value="SHOP ALL >">
        </div>
        <div class="shop-bbq">
            <span>Shop For BBQ's</span>
            <input type="button" class="shop-bbq-btn" name="shop-bbq-btn" value="SHOP >">
        </div>
        <div class="shop-roasts">
            <span>Shop Roasts</span>
            <input type="button" class="shop-roasts-btn" name="shop-roasts-btn" value="SHOP >">
        </div>
        <div class="shop-stew">
            <span>Shop For Stew</span>
            <input type="button" class="shop-stew-btn" name="shop-stew-btn" value="SHOP >">
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('mobile.nav') ?>